server:
  port: 8702 #服务注册中心端口号

logging:
  level:
    com.cloud.x20.openfeign: debug

spring:
  application:
    name: client-openfeign-service

## openfeign - 属性配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

