server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: my-spring-security
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
    encoding: UTF-8
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
