spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ego?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# 1. 基于@Configuration配置文档形式：
#     session.setTypeAliasesPackage("com.mybatis.dynamic.model")
#     session.setMapperLocations(resolver.getResources("classpath*:mapper/*.xml"))
# 2. 基于yml配置文档形式：
#     mapper-locations: classpath*:mapper/*.xml
#     type-aliases-package: com.mybatis.dynamic.model
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.mybatis.dynamic.model
  lazy-initialization: false