server:
  port: 8848

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    encoding: UTF-8
    cache: false
    suffix: .html
    servlet:
      content-type: text/html
  # 此配置适用于Resources目录下
  #  mvc:
  #    static-path-pattern: /static/**
  # 此配置适用于WebApp目录下
  resources:
    static-locations: classpath:/resources/, classpath:/static/, classpath:/public/
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/other?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.model
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



