## mysql 5.7+加载类 `com.mysql.jdbc.Driver'. ##
## mysql 8.0+这是弃用。新的驱动类是'  `com.mysql.cj.jdbc.Driver'. ##
## mysql 8.0+驱动程序是通过SPI自动注册的，手动加载驱动程序类通常是不必要的。 ##
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ego?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

## Action: ##
## Consider defining a bean of type 'org.**.dao.TbUserMapper' in your configuration. ##
## resources/mapper 非<配置在pom.xml中>：java/mapper ##
mybatis:
  mapper-locations: classpath*:/resources/mapper/*.xml
  type-aliases-package: com.liuweiwei.model