eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML5
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
      username: root
      password: 123456
  application:
    name: client-log4j-service

info:
  app.name: app-log4j-service
  company.name: app-log4j-service
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#logging:
#  # level: trace
#  # path: D:/logs/log4j
#  # file: D:/logs/log4j.log
#  file:
#    path: D:/logs/log4j
#    name: D:/logs/log4j/log4j.log
#  pattern:
#    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} -%msg%n"
#    file: "%d{yyyy/MM/dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} %msg%n"

logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace
