spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      # 配置扩展插件
      filters: stat,wall,log4j,config
      # 最大连接池数量，maxIdle已经不再使用
      max-active: 100
      # 初始化时建立物理连接的个数
      initial-size: 1
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 最小连接池数量
      min-idle: 1
      # 既作为检测的间隔时间又作为testWhileIdel执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql 必须是一个查询语句，mysql中为 select 'x'，oracle中为 select 1 from dual
      validation-query: select 'x'
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 当数据库抛出不可恢复的异常时,抛弃该连接
      # exception-sorter: true
      # 是否缓存preparedStatement,mysql5.5+建议开启
      pool-prepared-statements: true
      #
      max-open-prepared-statements: 50
      # 当值大于0时poolPreparedStatements会自动修改为true
      max-pool-prepared-statement-per-connection-size: 20
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 合并多个DruidDataSource的监控数据
      use-local-session-state: true
      # 设置访问druid监控页的账号和密码,默认没有
      stat-view-servlet:
        login-username: admin
        login-password: admin
    # driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    # username: root
    # password: 123456

### log config ###
#logging:
#  config: classpath:log4j.properties
