spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456

## Action: ##
## Consider defining a bean of type 'org.**.dao.TbUserMapper' in your configuration. ##
## resources/mapper 非<配置在pom.xml中>：java/mapper ##
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.liuweiwei.model