auth-server: http://localhost:8881/auth

server:
  servlet:
    context-path: /
  session:
    cookie:
        name: SESSION2

spring:
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: ${auth-server}/oauth/token
      userAuthorizationUri: ${auth-server}/oauth/authorize
    resource:
      userInfoUri: ${auth-server}/user