spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    mode: HTML
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 123456

#logging:
#  # level: trace
#  # path: D:/logs/logback
#  # file: D:/logs/logback-spring.log
#  file:
#    path: D:/logs/logback
#    name: D:/logs/logback/logback-spring.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} -%msg %n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} %msg %n"

logging:
  config: classpath:logback-spring.xml