server:
  port: 8701 #服务注册中心端口号

logging:
  level:
    com.cloud.x20.ribbon: debug

spring:
  application:
    name: client-ribbon-service

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

